# -*- coding: utf-8 -*-
"""EDA_final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fRr-ytsdS0up-vAgdNKFDMlJWyrBR89b

Parte 1: Cargar y mostrar el dataset

Esta parte te permite cargar el dataset desde Google Sheets y ver cómo está estructurado (columnas y primeras filas).
"""

import pandas as pd

# ID del documento y nombre de la hoja
sheet_id = "1IxBprEMZzej4c6InHyIkBqVjbgE7WtMK6dAHZNa47n0"
sheet_name = "dataset_final2"

# Construir la URL CSV
url = f"https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet={sheet_name}"

# Cargar dataset
df = pd.read_csv(url)

# Ver columnas y primeras filas
print("Columnas disponibles:")
print(df.columns.tolist())

df.head()

"""Parte 2: Ver resumen estadístico de los datos numéricos

Esto muestra estadísticas como media, desviación estándar, máximos y mínimos de columnas numéricas como velocidad, temperatura_motor, etc.
"""

df.describe()

"""Parte 3: Ver cuántos registros hay por bus (top 10)

Muestra cuáles son los 10 buses con más registros en el dataset.
"""

df['bus_id'].value_counts().head(10)

"""Parte 4: Visualizar los 10 buses con más registros

Genera una gráfica de barras para visualizar los buses más frecuentes en el dataset.
"""

import matplotlib.pyplot as plt

df['bus_id'].value_counts().head(10).plot(kind='bar', color='skyblue')
plt.title('Top 10 buses con más registros')
plt.xlabel('Bus ID')
plt.ylabel('Cantidad de registros')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

"""Parte 5: Ver la cantidad de alertas registradas

Esto muestra cuántas veces aparece cada tipo de alerta en el dataset. Por ejemplo, si hay "Exceso de velocidad", "Motor apagado", etc.
"""

df['alerta'].value_counts()

"""Parte 6: Visualización de alertas más comunes

Visualiza gráficamente los tipos de alertas que más se repiten.
"""

df['alerta'].value_counts().plot(kind='bar', color='salmon')
plt.title('Tipos de alertas más comunes')
plt.xlabel('Tipo de alerta')
plt.ylabel('Cantidad')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

"""Parte 7: Distribución de velocidad por bus (boxplot)

Este gráfico muestra la distribución de velocidades por cada bus (Top 5 más frecuentes), permitiendo identificar excesos o rangos típicos.
"""

import seaborn as sns
import matplotlib.pyplot as plt

# Filtrar solo los buses más frecuentes para mejor visualización
top_buses = df['bus_id'].value_counts().head(5).index
df_top_buses = df[df['bus_id'].isin(top_buses)]

plt.figure(figsize=(10, 6))
sns.boxplot(x='bus_id', y='velocidad', data=df_top_buses, palette="Blues")

plt.title("Distribución de velocidad por bus (Top 5)")
plt.xlabel("Bus ID")
plt.ylabel("Velocidad (km/h)")
plt.grid(True)
plt.tight_layout()
plt.show()