# -*- coding: utf-8 -*-
"""Extracion_Datos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qDo_Pycf_82ZmNMCsbaqGKsjQefYW-eu

**🚀EXTRACCIÓN DE DATOS DESDE GOOGLE SHEETS (EXCEL VIRTUAL)**


**Proyecto: Seguridad Operativa mediante GPS (Empresa: Transportes El Lorito)**

Instalar la librería pandas (opcional en Google Colab, pero lo incluimos por compatibilidad)
"""

!pip install --quiet gspread pandas gspread_dataframe

"""Nota:

Autenticación con Google (solo necesario si no usas un archivo público):

Si el archivo es público, puedes acceder con gspread sin autenticación compleja.

CELDA 1 – Código base general (solo ejecutar una vez al inicio)
"""

# Importamos la librería pandas, que permite trabajar con datos en forma de tablas (DataFrames)
import pandas as pd

# Definimos el ID único del archivo de Google Sheets
sheet_id = "1HBwyjBG0zH1AGpIXnKyFC26rGhSsIOF744vc6aSjfLE"

# Creamos una función para leer, mostrar y analizar una hoja específica del documento
def analizar_hoja(nombre_hoja, gid):
    """
    Esta función realiza:
    1. Construye el enlace CSV de exportación a partir del ID de hoja (gid)
    2. Lee el contenido como un DataFrame de pandas
    3. Muestra todos los datos completos de la hoja
    4. Muestra análisis básico como:
       - Total de filas y columnas
       - Nombres de las columnas
       - Tipo de datos por columna
       - Cantidad de valores faltantes por columna
    """

    # Construimos la URL directa para exportar la hoja como CSV
    url = f"https://docs.google.com/spreadsheets/d/{sheet_id}/export?format=csv&gid={gid}"

    # Leemos los datos desde la URL en formato CSV
    df = pd.read_csv(url)

    # Encabezado visual para identificar la hoja
    print("="*100)
    print(f"📋 HOJA: {nombre_hoja}")
    print("="*100)

    # Mostramos todos los datos completos (Google Colab los puede visualizar con display)
    print("🔹 Todos los datos:")
    display(df)

    # Mostramos dimensiones: cuántas filas y columnas tiene
    print(f"\n🔹 Filas: {df.shape[0]} | Columnas: {df.shape[1]}")

    # Mostramos el nombre de cada columna
    print("🔹 Columnas:", list(df.columns))

    # Mostramos el tipo de dato de cada columna (texto, número, fecha, etc.)
    print("\n🔹 Tipos de datos:")
    print(df.dtypes)

    # Mostramos cuántos valores vacíos hay por columna
    print("\n🔹 Valores nulos por columna:")
    print(df.isnull().sum())

"""✅ CELDAS SIGUIENTES – Una por cada hoja

📄 Cronograma
"""

analizar_hoja("Cronograma", "1002874041")

"""📄 Rutas"""

analizar_hoja("Rutas", "0")

"""📄 Buses"""

analizar_hoja("Buses", "1857142461")

"""📄 Falta"""

analizar_hoja("Falta", "1817979550")

"""📄 Inspector"""

analizar_hoja("Inspector", "540056938")

"""📄 Operador"""

analizar_hoja("Operador", "2013202462")

"""📄 Paradero"""

analizar_hoja("Paradero", "1205843695")

"""📄 Sanciones"""

analizar_hoja("Sanciones", "511629238")

"""📄 Sentido"""

analizar_hoja("Sentido", "1534440589")

"""📄 Detalle_sancion2024"""

analizar_hoja("Detalle_sancion2024", "351620038")

"""📄 Bd_Faltas2024"""

analizar_hoja("Bd_Faltas2024", "177512124")

"""Fuente 2: MongoDB (NoSQL)"""

!pip install pymongo --quiet

""" Estrategias de Limpieza"""

